minimum_pre_commit_version: "3.6.0"
default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json

  - repo: local
    hooks:
      - id: lint
        name: lint (pre-commit)
        entry: npm run lint
        language: system
        pass_filenames: false

      - id: typecheck
        name: typecheck (pre-commit)
        entry: npm run typecheck
        language: system
        pass_filenames: false

      - id: test
        name: test (pre-commit)
        entry: npm run test
        language: system
        pass_filenames: false
