export type TechnicalErrorCode = `E${number}${number}${number}${number}`;

export const TECHNICAL_ERROR_CODE_PATTERN = /^E\d{4}$/;

export function isTechnicalErrorCode(value: unknown): value is TechnicalErrorCode {
  return typeof value === "string" && TECHNICAL_ERROR_CODE_PATTERN.test(value);
}

export const TECHNICAL_ERROR_CODES = {
  API_UNEXPECTED_ERROR: "E1000",
  APPLICATION_SETTINGS_API_UNEXPECTED_ERROR: "E1001",
  EXCHANGE_RATES_SETTINGS_API_UNEXPECTED_ERROR: "E1002",
  LENDERS_API_UNEXPECTED_ERROR: "E1003",
  MONTHLY_EXPENSES_API_GET_UNEXPECTED_ERROR: "E1004",
  MONTHLY_EXPENSES_API_POST_UNEXPECTED_ERROR: "E1005",
  MONTHLY_EXPENSES_REPORT_API_UNEXPECTED_ERROR: "E1006",
  MONTHLY_EXPENSES_RECEIPTS_API_UPLOAD_UNEXPECTED_ERROR: "E1007",
  MONTHLY_EXPENSES_RECEIPTS_API_DELETE_UNEXPECTED_ERROR: "E1008",
  STORAGE_API_UNEXPECTED_ERROR: "E1009",
  GOOGLE_AUTHENTICATION_REQUIRED: "E1100",
  GOOGLE_OAUTH_CONFIGURATION_INCOMPLETE: "E1101",
  GOOGLE_DRIVE_API_DISABLED: "E1200",
  GOOGLE_DRIVE_INVALID_SCOPE: "E1201",
  GOOGLE_DRIVE_INSUFFICIENT_PERMISSIONS: "E1202",
  GOOGLE_DRIVE_INVALID_PAYLOAD: "E1203",
  TURSO_CONFIGURATION_INCOMPLETE: "E1300",
  MONTHLY_EXPENSES_SSR_UNEXPECTED_ERROR: "E1400",
  MONTHLY_EXPENSES_SSR_DOCUMENT_LOAD_ERROR: "E1401",
  MONTHLY_EXPENSES_SSR_LENDERS_LOAD_ERROR: "E1402",
  MONTHLY_EXPENSES_SSR_REPORT_LOAD_ERROR: "E1403",
  EXCHANGE_RATES_SSR_UNEXPECTED_ERROR: "E1404",
  EXCHANGE_RATES_SETTINGS_SSR_LOAD_ERROR: "E1405",
} as const satisfies Record<string, TechnicalErrorCode>;
